[quickstart] Fix domain name resolution failures on macOS
G-Research/siembol pull request #488
Opened 2022-01-13 13:18 UTC by jgiannuzzi

This PR aims at fixing the DNS resolution failures encountered on macOS with the quickstart guide.

The cause was the use of ingress FQDNs that don't share the same domain name (e.g. `storm.local` was not under `siembol.local`). This worked fine on Windows because all the ingress FQDNs are added as static IPs, but on macOS we use an actual DNS resolver that is registered only for the `siembol.local` domain name.

2022-01-13 14:04 UTC, mariannovotny requested changes
Hi @jgiannuzzi Thanks for this PR for fixing and cleaning dns names in quick start guide. Can you please check  in all scripts "*.local" and fix if needed - I think enrichments scripts are not included in this PR that should be.

2022-01-13 14:09 UTC, jgiannuzzi commented
Thanks @mariannovotny, good catch!

2022-01-14 16:33 UTC, mariannovotny approved these changes

2022-01-14 17:01 UTC, mariannovotny approved these changes
LGTM. Thanks

2022-01-14 17:34 UTC, merged